export const integrationData = {
  titular: {
    renda: "1234567",
    estadoCivil: "2",
    nacionalidade: "Brasileira",
    ufNaturalidade: "RJ",
    ufIdentidade: "RJ",
    profissao: "ADMINISTRADOR",
    tipoProfissao: "ASSALARIADO",
    resideNoImovel: "T",
  },
  conjuge: {
    nome: "CONJUGE CYPRESS INTEGRACAO",
    cpf: "63976666033",
    dataNascimento: "01012001",
    nacionalidade: "Brasileira",
    ufNaturalidade: "RJ",
    ufIdentidade: "RJ",
    dataComunhao: "01012025",
    regimeComunhao: "Comunhão Universal de Bens",
    ddd: "21",
    celular: "998071033",
    email: "conjuge.integracao@teste.com",
    renda: "1400000",
    profissao: "ADMINISTRADOR",
    tipoProfissao: "ASSALARIADO",
  },
  motivo: {
    finalidade: "Investir",
    descricao:
      "Pretendo organizar minhas finanças familiares e investir em melhorias importantes para nossa residência",
  },
  imovel: {
    uso: "Casa",
    tipo: "Residencial",
    condicao: "6",
    saldoDevedor: "25000000",
  },
  empresa: {
    razaoSocial: "EMPRESA CYPRESS INTEGRACAO LTDA",
    cnpj: "11222333000181",
    dataFundacao: "01012010",
    telefone: "987654321",
    email: "empresa.integracao@teste.com",
    cep: "01001000",
    endereco: "Praça da Sé",
    numero: "100",
    complemento: "SALA 10",
    bairro: "Sé",
    uf: "SP",
    municipio: "SÃO PAULO",
  },
  socios: [
    {
      nome: "SOCIO CYPRESS UM",
      cpf: "52998224725",
      dataNascimento: "01011990",
      ddd: "11",
      celular: "987654321",
      email: "socio.um@teste.com",
    },
    {
      nome: "SOCIO CYPRESS DOIS",
      cpf: "11144477735",
      dataNascimento: "02021992",
      ddd: "21",
      celular: "998765432",
      email: "socio.dois@teste.com",
    },
  ],
  cancelamento: {
    justificativa: "Cancelamento controlado para validacao automatizada das integracoes em desenvolvimento",
  },
} as const;
